### ISSUE TITLE
Improve Energy dashboard compatability

### ISSUE THREAD

**Issue by wimb0** [wimb0/home-assistant-saj-modbus#46]
I've been playing with the new Energy dashboard in Home Assistant 2021.8 and integration v1.5.0.
Apparently for the Solar production sensor to work, a new sensor which outputs kWh instead of W is needed.
It's not possible to select a live production value at the moment.
Will add a new sensor to fix this. Other ideas welcome!

![image](https://user-images.githubusercontent.com/11030068/128629254-c5dd5e1a-2877-4cbc-9603-1970a9c73a2d.png)

**Comment by fsaris** [comment]
The Total power generation works for me. It's in kWh

**Comment by fsaris** [comment]
Is the sensor active? Looks like it's disabled in your screenshot.

![IMG_20210808_130012](https://user-images.githubusercontent.com/4019341/128629748-e8f755e7-4049-425a-976b-37991c8d9ad7.jpg)
Here it's correctly selectable

**Comment by wimb0** [comment]
Yes, the sensor is active, but my Energy dashboard is weird.
![image](https://user-images.githubusercontent.com/11030068/128629803-0ff98643-615c-4413-9e15-a13bb64e8de9.png)

The Total power generation is the total of what the Inverter has generated over its lifetime.
Maybe I'm wrong, but isn't the Energy dashboard based on live usage and production values?

My idea was to have high/low tariff values (From DSMR Reader via MQTT) as usage and Active power of inverter total output as production.

**Comment by fsaris** [comment]
Here the info you should see in the developers tool

![Screenshot_2021-08-08-13-09-53-120_com android chrome](https://user-images.githubusercontent.com/4019341/128629991-a14cd97e-31dd-4558-9206-3c73a1a88650.jpg)

**Comment by wimb0** [comment]
I guess I misunderstood how the Energy dashboard works, documentation is not really helpful.
I think you also have the meter totals as usage values?

**Comment by wimb0** [comment]
![image](https://user-images.githubusercontent.com/11030068/128630778-b51c914a-4e4b-4ec6-b7a4-48fe1fc161e2.png)

Think I've got it working. Thanks @fsaris for the replies, they sent me in the right way.

I'll close this issue, as does not seem to be needed.
