### ISSUE TITLE
Huawei SUN2000 (17)KTL-M0 / Elfin EW11A

### ISSUE THREAD

**Issue by Marchellos** [wimb0/home-assistant-saj-modbus#58]
Hello,

I don't see any other option to ask this way:
Let me know if I had to ask another way.

Is this method also possible for the [Huawei SUN2000 (17)KTL-M0](https://support.huawei.com/enterprise/en/doc/EDOC1100092106/19088147/de-rs485-communicatiekabel-aansluiten-smart-power-sensor)?

Can it be made suitable for the HUAWEI (I have no knowledge for this) ?

How should the wiring be connected for this with RJ45 4PIN Connector,  [see manuel pages 12 and 15 of the EW11A](http://www.hi-flying.com/elfin-ew10-elfin-ew11).

**Comment by wimb0** [comment]
Hi,
This integration is not able to work with your Huawei inverter.
Maybe you can ask here: https://github.com/Emilv2/huawei_solar
That seems to be an integration for Huawei inverters.
