### ISSUE TITLE
Compatible with SAJ H1 Hybrid inverters

### ISSUE THREAD

**Issue by moreto84** [wimb0/home-assistant-saj-modbus#59]
Hi,  Many thanks for your work.

Writting from spain, I got a H1 Hybrid inverter. Do you have any experience with this version?

I've been told that terminal supports Modbus, but I'd need to take out the Wifi Antenna and then I'd loose the statistics and the portal of the manufacturer. The issue is that it refreshes every 5 minutes and I'd need something with about 5-10 seconds.

Thanks!

**Comment by wimb0** [comment]
Hi,

I do not know if this integration will work with your inverter.
At the moment it's only known to work with SAJ R5, Sununo and Suntrio inverters.
Can't find any modbus documentation for your H1 Hybrid inverter.
If you have documentation, maybe we can make the integration compatible.

Maybe it works, maybe it won't.
You can test what works.

**Comment by manumora** [comment]
I think H1 doesn't work with RS485 TCP but maybe it can work with RS485 RTU, it is through RJ45 interface that provide H1 inverter. I am working on it.

**Comment by wimb0** [comment]
Did you have any luck getting data out of the H1 inverter via modbus?

**Comment by wimb0** [comment]
no reply. closing issue.
