### ISSUE TITLE
SAJ Modbus weird addresses

### ISSUE THREAD

**Issue by manumora** [wimb0/home-assistant-saj-modbus#60]
I would like to start to monitorize my SAJ inverter using node-red. To get the value of some item (for instance: "L2 voltaje") the pdf file show that it has the address 011CH. However that is an strange address, node-red only allows decimals numbers. Even that is not an hexadecimal value. Can you help me?

**Comment by wimb0** [comment]
I cannot help you with that. Please only post issues regarding this integration.
