### ISSUE TITLE
Saj inverter R5 not giving data

### ISSUE THREAD

**Issue by sirkserac** [wimb0/home-assistant-saj-modbus#62]
Hello, i'm trying to do a read of the rs485 port on the saj r5 inverter but dont get data, i wired the cable like you show in your image, their is a lot i can configur in the converter i'm using   maybe i have a config issue. I use the USR-Tcp232-410s and it supports rs232, rs485 modbus rtu to modbus tcp.

Any advice?

Thanks anyway for this post .

**Comment by wimb0** [comment]
Good to hear you got it solved.
I do not have any info about the saj battery, thus I cannot help you with that.
