### ISSUE TITLE
Integration not working

### ISSUE THREAD

**Issue by matly006** [wimb0/home-assistant-saj-modbus#74]
hi, after an unwanted update from saj I find my integration made with nodered and mqtt no longer working. I therefore purchased the RS485 EW11 converter and connected it as per the diagram, however I cannot extrapolate any data that is familiar to me. I rechecked the device configuration and it is correct. Do you have any suggestions?

my inverter is h1 2x5kw batteries

first, to collect the data, I intercepted the mqtt packets sent from the wireless stick to the saj servers, converted the modbus registers and had all the values. Now it doesn't work anymore and the bad thing is that saj doesn't answer me in any way, whether by phone or email.

I thank everyone who will help me

**Comment by wimb0** [comment]
Closed, because stale.
