### ISSUE TITLE
Issue while calculating the PV production

### ISSUE THREAD

**Issue by Arise** [wimb0/home-assistant-saj-modbus#88]
I've noticed that from time to time, even without an error described in other bug reports my [tesla-style-solar-power-card](https://github.com/reptilex/tesla-style-solar-power-card) shows **0** for the PV production. 

Not sure if there is something in how I compute the sensors, but this is the problem I see frequently when the saj modbus integration takes longer time (like multiple 5 seconds) to process the message.

![image](https://github.com/wimb0/home-assistant-saj-modbus/assets/510392/e0d05101-6c2b-4a63-97aa-0f13be932917)

**Comment by mvn23** [comment]
Disconnect your SEC and see if the problems persist...

**Comment by Arise** [comment]
Issue fixed as well.
